language: php

services:
  - docker

before_install:
- docker login --username $DOCKER_USER -p$DOCKER_PASS
- docker build -t ossprojects/app-core:hbutow-test .
- docker push ossprojects/app-core:hbutow-test
